/**:
  ros__parameters:
    min_longitudinal_offset: -0.1
    max_longitudinal_offset: 0.85
    min_lateral_offset: -0.30
    max_lateral_offset: 0.30
    min_height_offset: 0.1
    max_height_offset: 1.5
    